---
title: "Homework 2: Poisson Regression Examples"
author: "Alex Wissman"
date: today
callout-appearance: minimal # this hides the blue "i" icon on .callout-notes
---


## Blueprinty Case Study

### Introduction

Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty's software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty's software and after using it. Unfortunately, such data is not available. 

However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm's number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty's software. The marketing team would like to use this data to make the claim that firms using Blueprinty's software are more successful in getting their patent applications approved.


### Data
```{python}
import pandas as pd

# Load the datasets
airbnb_data = pd.read_csv('/home/jovyan/mysite/airbnb.csv')
blueprinty_data = pd.read_csv('/home/jovyan/mysite/blueprinty.csv')

# Display the first few rows of each dataset
airbnb_data.head(), blueprinty_data.head()
```